# Generated by Django 5.2.4 on 2025-08-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('grocery', 'Grocery'), ('books', 'Books'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
