# Generated by Django 5.2.4 on 2025-08-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('grocery', 'Grocery'), ('books', 'Books'), ('footwear', 'Footwear'), ('bag', 'Bag'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
